# -*- coding: utf-8 -*-
"""foodseg103_training_ccnet_resnet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpdR8CM6YYWpdZeC5YWXBe9sUFm45Iy-

# FoodSeg103 Semantic Segmentation with CCNet-Style ResNet-50

This notebook trains a CCNet-style semantic segmentation model with a ResNet-50 backbone on FoodSeg103.
"""

# Optional installs (uncomment if needed)
# %pip install opencv-python albumentations
# %pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# ============================================================
# ONE-CELL COLAB: CCNet + ResNet50 for FoodSeg103 benchmark-style
# ============================================================

# -----------------------------
# Install deps
# -----------------------------
# !pip -q install kagglehub pandas matplotlib pillow

import gc
import torch

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

# -----------------------------
# CONFIG (ALL AT TOP)
# -----------------------------
from pathlib import Path
import torch
import os

CFG = {
    # =====================================================
    # General
    # =====================================================
    "seed": 42,
    "device": "cuda" if torch.cuda.is_available() else "cpu",
    "amp": True,
    "cudnn_benchmark": True,

    # =====================================================
    # Google Drive / paths
    # =====================================================
    "mount_drive": True,
    "work_dir": "/content/drive/MyDrive/[PROJECT][COMPUTER-VISION]/ccnet_resnet50_foodseg103_benchmark",
    "resume": False,
    "save_last_name": "last.pth",
    "save_best_name": "best_miou.pth",
    "metrics_csv_name": "metrics.csv",
    "config_json_name": "config.json",

    # =====================================================
    # Dataset
    # =====================================================
    "kaggle_dataset": "arischii05/foodseg103-fullmask",
    "expected_subdirs": [
        "foodseg103-full",
        "foodseg103_rebalanced",
        "cleaned-foodseg103",
        "foodseg103",
    ],
    "data_root": "/content/data/foodseg103-full",

    "train_img_dir": "train/img",
    "train_mask_dir": "train/mask",
    "val_img_dir": "test/img",
    "val_mask_dir": "test/mask",

    # fallback values; auto override if class_mapping.json exists
    "num_classes": 104,
    "ignore_index": 255,
    "background_id": 103,
    "auto_infer_class_mapping": True,
    "image_exts": [".jpg", ".jpeg", ".png", ".bmp", ".webp"],

    # =====================================================
    # Model: CCNet
    # =====================================================
    "model_name": "ccnet",
    "backbone_name": "resnet50",
    "backbone_pretrained": True,
    "freeze_backbone": False,
    "output_stride": 8,              # dilated ResNet
    "cc_recurrence": 2,              # RCCA R=2
    "rcca_channels": 512,
    # "use_aux_head": True,
    "use_aux_head": False,
    "aux_weight": 0.4,
    "dropout": 0.1,

    # =====================================================
    # Input / augmentation
    # FoodSeg103 benchmark-style training recipe
    # =====================================================
    "train_size": (512, 512),
    "val_size": (512, 512),        # fixed-size eval for stable batching; set None if you want original size + batch_size=1
    "scale_range": (0.5, 2.0),
    "hflip_prob": 0.5,
    "use_color_jitter": True,
    "color_jitter_p": 0.8,
    "color_jitter_brightness": 0.2,
    "color_jitter_contrast": 0.2,
    "color_jitter_saturation": 0.2,
    "color_jitter_hue": 0.05,
    "imagenet_mean": [0.485, 0.456, 0.406],
    "imagenet_std": [0.229, 0.224, 0.225],

    # =====================================================
    # Dataloader
    # =====================================================
    "batch_size": 8,
    "eval_batch_size": 1,
    "num_workers": 0,
    "pin_memory": False,
    "drop_last": True,

    # =====================================================
    # Optimizer / scheduler
    # =====================================================
    "epochs": 10,
    "lr": 1e-3,
    "momentum": 0.9,
    "weight_decay": 5e-4,
    "poly_power": 0.9,
    "grad_clip_norm": None,

    # =====================================================
    # Logging / eval
    # =====================================================
    "print_freq": 20,
    "eval_every": 1,

    # =====================================================
    # Overfit mode
    # =====================================================
    "overfit_mode": False,
    "overfit_num_samples": 32,        # 8 or 32
    "overfit_eval_on_train": True,
    "overfit_disable_scale": True,
    "overfit_disable_hflip": True,
    "overfit_disable_color_jitter": True,

    # =====================================================
    # Visualization / debug
    # =====================================================
    "num_vis": 4,
}

# ============================================================
# IMPORTS
# ============================================================
import json
import math
import time
import copy
import random
import shutil
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image
import kagglehub

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import models
from torchvision.models import ResNet50_Weights
from torchvision.transforms import functional as TF
import torchvision.transforms as T

from tqdm.auto import tqdm

# ============================================================
# DRIVE
# ============================================================
if CFG["mount_drive"]:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=True)

# ============================================================
# REPRODUCIBILITY
# ============================================================
def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

seed_everything(CFG["seed"])
torch.backends.cudnn.benchmark = CFG["cudnn_benchmark"]

# ============================================================
# PATH HELPERS
# ============================================================
def get_paths(cfg: dict) -> dict:
    root = Path(cfg["data_root"])
    return {
        "root": root,
        "train_img_dir": root / cfg["train_img_dir"],
        "train_mask_dir": root / cfg["train_mask_dir"],
        "val_img_dir": root / cfg["val_img_dir"],
        "val_mask_dir": root / cfg["val_mask_dir"],
        "work_dir": Path(cfg["work_dir"]),
    }

# ============================================================
# DOWNLOAD DATASET FROM KAGGLE + SYMLINK
# ============================================================
print("=" * 100)
print("Downloading dataset from Kaggle...")
dataset_root = Path(kagglehub.dataset_download(CFG["kaggle_dataset"]))
print("Kaggle dataset root:", dataset_root)

candidates = []
for name in CFG["expected_subdirs"]:
    p = dataset_root / name
    if p.exists():
        candidates.append(p)

if not candidates:
    for p in dataset_root.rglob("*"):
        if p.is_dir() and p.name in CFG["expected_subdirs"]:
            candidates.append(p)

if not candidates:
    for p in dataset_root.rglob("*"):
        if p.is_dir() and (p / "train" / "img").exists() and (p / "train" / "mask").exists():
            candidates.append(p)

if len(candidates) == 0:
    raise FileNotFoundError(f"Cannot resolve dataset root from {dataset_root}")

candidates = sorted(candidates, key=lambda x: len(str(x)))
real_data_root = candidates[0]

expected_path = Path(CFG["data_root"])
expected_path.parent.mkdir(parents=True, exist_ok=True)

if expected_path.exists() or expected_path.is_symlink():
    if expected_path.is_symlink() or expected_path.is_file():
        expected_path.unlink()
    else:
        shutil.rmtree(expected_path)

expected_path.symlink_to(real_data_root, target_is_directory=True)

print("Resolved real_data_root:", real_data_root)
print("Symlink path:", expected_path)
print("=" * 100)

# ============================================================
# AUTO-INFER CLASS MAPPING
# ============================================================
if CFG["auto_infer_class_mapping"]:
    mapping_candidates = [
        expected_path / "class_mapping.json",
        expected_path / "metadata" / "class_mapping.json",
    ]
    mapping_path = None
    for mp in mapping_candidates:
        if mp.exists():
            mapping_path = mp
            break

    if mapping_path is not None:
        print(f"[INFO] Found class_mapping.json: {mapping_path}")
        with open(mapping_path, "r", encoding="utf-8") as f:
            mapping = json.load(f)

        if "num_classes" in mapping:
            CFG["num_classes"] = int(mapping["num_classes"])

        if "background_id" in mapping:
            CFG["background_id"] = int(mapping["background_id"])

        if "id_to_class" in mapping:
            id_to_class = {int(k): v for k, v in mapping["id_to_class"].items()}
        else:
            id_to_class = {i: f"class_{i}" for i in range(CFG["num_classes"])}
    else:
        print("[WARN] class_mapping.json not found. Using fallback num_classes/background_id from CFG.")
        id_to_class = {i: f"class_{i}" for i in range(CFG["num_classes"])}
else:
    id_to_class = {i: f"class_{i}" for i in range(CFG["num_classes"])}

class_names = [id_to_class.get(i, f"class_{i}") for i in range(CFG["num_classes"])]

PATHS = get_paths(CFG)
PATHS["work_dir"].mkdir(parents=True, exist_ok=True)

LAST_CKPT = PATHS["work_dir"] / CFG["save_last_name"]
BEST_CKPT = PATHS["work_dir"] / CFG["save_best_name"]
METRICS_CSV = PATHS["work_dir"] / CFG["metrics_csv_name"]
CONFIG_JSON = PATHS["work_dir"] / CFG["config_json_name"]

with open(CONFIG_JSON, "w", encoding="utf-8") as f:
    json.dump(CFG, f, indent=2, ensure_ascii=False)

print(f"[INFO] work_dir: {PATHS['work_dir']}")
print(f"[INFO] num_classes: {CFG['num_classes']}")
print(f"[INFO] background_id: {CFG['background_id']}")
print(f"[INFO] device: {CFG['device']}")

# ============================================================
# DATA DISCOVERY
# ============================================================
IMG_EXTS = tuple([x.lower() for x in CFG["image_exts"]])

def find_image_path(img_dir: Path, stem: str):
    for ext in CFG["image_exts"]:
        p = img_dir / f"{stem}{ext}"
        if p.exists():
            return p
    return None

def collect_samples(img_dir: Path, mask_dir: Path):
    samples = []
    for p in sorted(img_dir.iterdir()):
        if p.is_file() and p.suffix.lower() in IMG_EXTS:
            stem = p.stem
            mask_path = mask_dir / f"{stem}.png"
            if mask_path.exists():
                samples.append((str(p), str(mask_path), stem))
    return samples

train_samples = collect_samples(PATHS["train_img_dir"], PATHS["train_mask_dir"])
val_samples = collect_samples(PATHS["val_img_dir"], PATHS["val_mask_dir"])

if len(train_samples) == 0:
    raise RuntimeError("No training samples found")
if len(val_samples) == 0:
    raise RuntimeError("No validation samples found")

print(f"[INFO] train_samples: {len(train_samples)}")
print(f"[INFO] val_samples  : {len(val_samples)}")

if CFG["overfit_mode"]:
    n = min(CFG["overfit_num_samples"], len(train_samples))
    train_samples = train_samples[:n]
    if CFG["overfit_eval_on_train"]:
        val_samples = train_samples.copy()
    else:
        val_samples = val_samples[:n]
    print(f"[OVERFIT MODE] using {len(train_samples)} train samples and {len(val_samples)} val samples")

# ============================================================
# TRANSFORMS
# ============================================================
MEAN = CFG["imagenet_mean"]
STD = CFG["imagenet_std"]

def maybe_color_jitter(img):
    if CFG["use_color_jitter"] and random.random() < CFG["color_jitter_p"]:
        jitter = T.ColorJitter(
            brightness=CFG["color_jitter_brightness"],
            contrast=CFG["color_jitter_contrast"],
            saturation=CFG["color_jitter_saturation"],
            hue=CFG["color_jitter_hue"],
        )
        img = jitter(img)
    return img

class TrainTransform:
    def __call__(self, image, mask):
        do_scale = not (CFG["overfit_mode"] and CFG["overfit_disable_scale"])
        do_hflip = not (CFG["overfit_mode"] and CFG["overfit_disable_hflip"])
        do_cj = not (CFG["overfit_mode"] and CFG["overfit_disable_color_jitter"])

        if do_scale:
            lo, hi = CFG["scale_range"]
            ratio = random.uniform(lo, hi)
            nw = max(32, int(image.size[0] * ratio))
            nh = max(32, int(image.size[1] * ratio))
            image = image.resize((nw, nh), Image.BILINEAR)
            mask = mask.resize((nw, nh), Image.NEAREST)

        if do_hflip and random.random() < CFG["hflip_prob"]:
            image = TF.hflip(image)
            mask = TF.hflip(mask)

        if do_cj:
            image = maybe_color_jitter(image)

        crop_h, crop_w = CFG["train_size"]
        pad_h = max(0, crop_h - image.size[1])
        pad_w = max(0, crop_w - image.size[0])

        if pad_h > 0 or pad_w > 0:
            image = TF.pad(image, [0, 0, pad_w, pad_h], fill=0)
            mask = TF.pad(mask, [0, 0, pad_w, pad_h], fill=CFG["ignore_index"])

        i, j, h, w = T.RandomCrop.get_params(image, output_size=(crop_h, crop_w))
        image = TF.crop(image, i, j, h, w)
        mask = TF.crop(mask, i, j, h, w)

        image = TF.to_tensor(image)
        image = TF.normalize(image, mean=MEAN, std=STD)

        mask = torch.from_numpy(np.array(mask, dtype=np.int64))
        invalid = (mask < 0) | (mask >= CFG["num_classes"])
        mask[invalid] = CFG["ignore_index"]

        return image, mask

class ValTransform:
    def __call__(self, image, mask):
        if CFG["val_size"] is not None:
            vh, vw = CFG["val_size"]
            image = image.resize((vw, vh), Image.BILINEAR)
            mask = mask.resize((vw, vh), Image.NEAREST)

        image = TF.to_tensor(image)
        image = TF.normalize(image, mean=MEAN, std=STD)

        mask = torch.from_numpy(np.array(mask, dtype=np.int64))
        invalid = (mask < 0) | (mask >= CFG["num_classes"])
        mask[invalid] = CFG["ignore_index"]

        return image, mask

# ============================================================
# DATASET
# ============================================================
class FoodSegDataset(Dataset):
    def __init__(self, samples, transform):
        self.samples = samples
        self.transform = transform

    def __len__(self):
        return len(self.samples)

    # def __getitem__(self, idx):
    #     img_path, mask_path, stem = self.samples[idx]
    #     image = Image.open(img_path).convert("RGB")
    #     mask = Image.open(mask_path)
    #     image, mask = self.transform(image, mask)
    #     return image, mask, stem, img_path, mask_path

    def __getitem__(self, idx):
            img_path, mask_path, stem = self.samples[idx]
            try:
                image = Image.open(img_path).convert("RGB")
                mask = Image.open(mask_path)
                image, mask = self.transform(image, mask)
                return image, mask, stem, img_path, mask_path
            except Exception as e:
                print(f"[DATA ERROR] idx={idx} stem={stem}")
                print(f"  img_path={img_path}")
                print(f"  mask_path={mask_path}")
                print(f"  error={repr(e)}")
                raise

def val_collate(batch):
    images, masks, stems, img_paths, mask_paths = zip(*batch)
    return torch.stack(images, 0), torch.stack(masks, 0), list(stems), list(img_paths), list(mask_paths)

train_loader = DataLoader(
    FoodSegDataset(train_samples, TrainTransform()),
    batch_size=CFG["batch_size"],
    shuffle=True,
    num_workers=CFG["num_workers"],
    pin_memory=CFG["pin_memory"],
    drop_last=CFG["drop_last"],
)

val_loader = DataLoader(
    FoodSegDataset(val_samples, ValTransform()),
    batch_size=CFG["eval_batch_size"] if CFG["val_size"] is not None else 1,
    shuffle=False,
    num_workers=CFG["num_workers"],
    pin_memory=CFG["pin_memory"],
    drop_last=False,
    collate_fn=val_collate,
)

# ============================================================
# MODEL: CCNet
# ============================================================
class ConvBNReLU(nn.Module):
    def __init__(self, in_ch, out_ch, k=3, s=1, p=1, d=1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size=k, stride=s, padding=p, dilation=d, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )
    def forward(self, x):
        return self.block(x)

def INF(B, H, W, device):
    # mask diagonal for row attention
    return -torch.diag(torch.full((H,), 1e9, device=device), diagonal=0).unsqueeze(0).repeat(B * W, 1, 1)

class CrissCrossAttention(nn.Module):
    def __init__(self, in_dim):
        super().__init__()
        inter_dim = max(1, in_dim // 8)
        self.query_conv = nn.Conv2d(in_dim, inter_dim, kernel_size=1)
        self.key_conv = nn.Conv2d(in_dim, inter_dim, kernel_size=1)
        self.value_conv = nn.Conv2d(in_dim, in_dim, kernel_size=1)
        self.softmax = nn.Softmax(dim=3)
        self.gamma = nn.Parameter(torch.zeros(1))

    def forward(self, x):
        m_batchsize, _, height, width = x.size()
        proj_query = self.query_conv(x)
        proj_key = self.key_conv(x)
        proj_value = self.value_conv(x)

        # H attention
        proj_query_H = proj_query.permute(0, 3, 1, 2).contiguous().view(m_batchsize * width, -1, height).permute(0, 2, 1)
        proj_key_H = proj_key.permute(0, 3, 1, 2).contiguous().view(m_batchsize * width, -1, height)
        proj_value_H = proj_value.permute(0, 3, 1, 2).contiguous().view(m_batchsize * width, -1, height)

        energy_H = torch.bmm(proj_query_H, proj_key_H) + INF(m_batchsize, height, width, x.device)
        energy_H = energy_H.view(m_batchsize, width, height, height).permute(0, 2, 1, 3)

        # W attention
        proj_query_W = proj_query.permute(0, 2, 1, 3).contiguous().view(m_batchsize * height, -1, width).permute(0, 2, 1)
        proj_key_W = proj_key.permute(0, 2, 1, 3).contiguous().view(m_batchsize * height, -1, width)
        proj_value_W = proj_value.permute(0, 2, 1, 3).contiguous().view(m_batchsize * height, -1, width)

        energy_W = torch.bmm(proj_query_W, proj_key_W)
        energy_W = energy_W.view(m_batchsize, height, width, width)

        concate = self.softmax(torch.cat([energy_H, energy_W], dim=3))

        att_H = concate[:, :, :, 0:height].permute(0, 2, 1, 3).contiguous().view(m_batchsize * width, height, height)
        att_W = concate[:, :, :, height:height + width].contiguous().view(m_batchsize * height, width, width)

        out_H = torch.bmm(proj_value_H, att_H.permute(0, 2, 1))
        out_H = out_H.view(m_batchsize, width, -1, height).permute(0, 2, 3, 1)

        out_W = torch.bmm(proj_value_W, att_W.permute(0, 2, 1))
        out_W = out_W.view(m_batchsize, height, -1, width).permute(0, 2, 1, 3)

        out = self.gamma * (out_H + out_W) + x
        return out

class RCCAModule(nn.Module):
    def __init__(self, in_channels, out_channels, recurrence=2):
        super().__init__()
        self.recurrence = recurrence
        self.conva = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )
        self.cca = CrissCrossAttention(out_channels)
        self.convb = nn.Sequential(
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        out = self.conva(x)
        for _ in range(self.recurrence):
            out = self.cca(out)
        out = self.convb(out)
        return out

class FCNHead(nn.Module):
    def __init__(self, in_channels, channels, num_classes, dropout=0.1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(channels),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout),
            nn.Conv2d(channels, num_classes, kernel_size=1),
        )
    def forward(self, x):
        return self.block(x)

class ResNetDilatedBackbone(nn.Module):
    def __init__(self, pretrained=True):
        super().__init__()
        weights = ResNet50_Weights.IMAGENET1K_V2 if pretrained else None
        base = models.resnet50(weights=weights, replace_stride_with_dilation=[False, True, True])

        self.conv1 = base.conv1
        self.bn1 = base.bn1
        self.relu = base.relu
        self.maxpool = base.maxpool
        self.layer1 = base.layer1
        self.layer2 = base.layer2
        self.layer3 = base.layer3
        self.layer4 = base.layer4

        self.out_channels = 2048
        self.aux_channels = 1024

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)     # /4
        x = self.layer1(x)      # /4
        x = self.layer2(x)      # /8
        aux = self.layer3(x)    # /8 with dilation
        out = self.layer4(aux)  # /8 with dilation
        return out, aux

class CCNetSeg(nn.Module):
    def __init__(self, num_classes, recurrence=2, pretrained=True, aux=True, dropout=0.1):
        super().__init__()
        self.backbone = ResNetDilatedBackbone(pretrained=pretrained)
        self.rcca = RCCAModule(self.backbone.out_channels, CFG["rcca_channels"], recurrence=recurrence)
        self.cls_head = FCNHead(CFG["rcca_channels"], 512, num_classes, dropout=dropout)
        self.use_aux = aux
        if self.use_aux:
            self.aux_head = FCNHead(self.backbone.aux_channels, 256, num_classes, dropout=dropout)

    def forward(self, x):
        input_size = x.shape[-2:]
        feat, aux_feat = self.backbone(x)
        feat = self.rcca(feat)
        logits = self.cls_head(feat)
        logits = F.interpolate(logits, size=input_size, mode="bilinear", align_corners=False)

        if self.use_aux:
            aux_logits = self.aux_head(aux_feat)
            aux_logits = F.interpolate(aux_logits, size=input_size, mode="bilinear", align_corners=False)
            return logits, aux_logits
        return logits

# ============================================================
# BUILD MODEL
# ============================================================
model = CCNetSeg(
    num_classes=CFG["num_classes"],
    recurrence=CFG["cc_recurrence"],
    pretrained=CFG["backbone_pretrained"],
    aux=CFG["use_aux_head"],
    dropout=CFG["dropout"],
).to(CFG["device"])

if CFG["freeze_backbone"]:
    for p in model.backbone.parameters():
        p.requires_grad = False

criterion = nn.CrossEntropyLoss(ignore_index=CFG["ignore_index"])

optimizer = torch.optim.SGD(
    [p for p in model.parameters() if p.requires_grad],
    lr=CFG["lr"],
    momentum=CFG["momentum"],
    weight_decay=CFG["weight_decay"],
)

scaler = torch.cuda.amp.GradScaler(enabled=CFG["amp"] and CFG["device"].startswith("cuda"))

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"[MODEL] total_params: {total_params:,}")
print(f"[MODEL] trainable_params: {trainable_params:,}")

# dry run
with torch.no_grad():
    dummy = torch.randn(2, 3, CFG["train_size"][0], CFG["train_size"][1]).to(CFG["device"])
    out = model(dummy)
    if isinstance(out, tuple):
        print("[DRY RUN] main:", tuple(out[0].shape), "aux:", tuple(out[1].shape))
    else:
        print("[DRY RUN] logits:", tuple(out.shape))

# ============================================================
# CHECKPOINT HELPERS
# ============================================================
def save_checkpoint(path, epoch, best_miou, global_step):
    torch.save({
        "epoch": epoch,
        "best_miou": best_miou,
        "global_step": global_step,
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "scaler": scaler.state_dict(),
        "cfg": CFG,
        "class_names": class_names,
    }, path)

start_epoch = 0
best_miou = -1.0
global_step = 0

if CFG["resume"] and LAST_CKPT.exists():
    print(f"[RESUME] Loading: {LAST_CKPT}")
    ckpt = torch.load(LAST_CKPT, map_location=CFG["device"])
    model.load_state_dict(ckpt["model"], strict=True)
    optimizer.load_state_dict(ckpt["optimizer"])
    scaler.load_state_dict(ckpt["scaler"])
    start_epoch = ckpt["epoch"] + 1
    best_miou = ckpt.get("best_miou", -1.0)
    global_step = ckpt.get("global_step", 0)
    print(f"[RESUME] start_epoch={start_epoch}, best_miou={best_miou:.6f}, global_step={global_step}")
else:
    print("[RESUME] Training from scratch.")

# ============================================================
# LR SCHEDULE
# ============================================================
iters_per_epoch = max(1, len(train_loader))
max_iters = CFG["epochs"] * iters_per_epoch

def poly_lr(base_lr, cur_iter, max_iter, power=0.9):
    return base_lr * ((1 - float(cur_iter) / max_iter) ** power)

def set_lr(optimizer, lr):
    for param_group in optimizer.param_groups:
        param_group["lr"] = lr

# ============================================================
# METRICS
# ============================================================
@torch.no_grad()
def fast_hist(pred, target, num_classes, ignore_index=255):
    mask = target != ignore_index
    pred = pred[mask]
    target = target[mask]
    k = (target >= 0) & (target < num_classes)
    inds = num_classes * target[k].to(torch.int64) + pred[k]
    hist = torch.bincount(inds, minlength=num_classes**2).reshape(num_classes, num_classes)
    return hist

@torch.no_grad()
def compute_scores(hist):
    hist = hist.float()
    diag = torch.diag(hist)
    gt_sum = hist.sum(dim=1)
    pred_sum = hist.sum(dim=0)
    total = hist.sum().clamp_min(1.0)

    aAcc = diag.sum() / total
    acc_cls = diag / gt_sum.clamp_min(1.0)
    iu = diag / (gt_sum + pred_sum - diag).clamp_min(1.0)

    present = gt_sum > 0
    mAcc = acc_cls[present].mean() if present.any() else torch.tensor(0.0, device=hist.device)
    mIoU = iu[present].mean() if present.any() else torch.tensor(0.0, device=hist.device)

    fg_present = present.clone()
    if CFG["background_id"] < len(fg_present):
        fg_present[CFG["background_id"]] = False

    mAcc_fg = acc_cls[fg_present].mean() if fg_present.any() else torch.tensor(0.0, device=hist.device)
    mIoU_fg = iu[fg_present].mean() if fg_present.any() else torch.tensor(0.0, device=hist.device)

    return {
        "aAcc": float(aAcc.item()),
        "mAcc": float(mAcc.item()),
        "mIoU": float(mIoU.item()),
        "mAcc_fg": float(mAcc_fg.item()),
        "mIoU_fg": float(mIoU_fg.item()),
        "iou_per_class": iu.cpu().numpy(),
        "acc_per_class": acc_cls.cpu().numpy(),
        "gt_sum": gt_sum.cpu().numpy(),
        "pred_sum": pred_sum.cpu().numpy(),
    }

# ============================================================
# TRAIN / EVAL
# ============================================================
def train_one_epoch(epoch):
    model.train()
    running_loss = 0.0

    pbar = tqdm(enumerate(train_loader), total=len(train_loader), desc=f"Train {epoch:03d}")
    for it, (images, masks, stems, _, _) in pbar:
        global global_step
        images = images.to(CFG["device"], non_blocking=True)
        masks = masks.to(CFG["device"], non_blocking=True)

        cur_iter = epoch * iters_per_epoch + it
        lr = poly_lr(CFG["lr"], cur_iter, max_iters, CFG["poly_power"])
        set_lr(optimizer, lr)

        optimizer.zero_grad(set_to_none=True)

        with torch.cuda.amp.autocast(enabled=CFG["amp"] and CFG["device"].startswith("cuda")):
            outputs = model(images)
            if isinstance(outputs, tuple):
                logits, aux_logits = outputs
                loss_main = criterion(logits, masks)
                loss_aux = criterion(aux_logits, masks)
                loss = loss_main + CFG["aux_weight"] * loss_aux
            else:
                logits = outputs
                loss_main = criterion(logits, masks)
                loss_aux = torch.tensor(0.0, device=images.device)
                loss = loss_main

        scaler.scale(loss).backward()

        if CFG["grad_clip_norm"] is not None:
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(model.parameters(), CFG["grad_clip_norm"])

        scaler.step(optimizer)
        scaler.update()

        running_loss += float(loss.item())
        global_step += 1

        if (it + 1) % CFG["print_freq"] == 0 or (it + 1) == len(train_loader):
            pbar.set_postfix({
                "loss": f"{loss.item():.4f}",
                "main": f"{loss_main.item():.4f}",
                "aux": f"{loss_aux.item():.4f}",
                "lr": f"{lr:.6f}",
            })

    return running_loss / max(1, len(train_loader))

@torch.no_grad()
def evaluate(epoch):
    model.eval()
    hist = torch.zeros((CFG["num_classes"], CFG["num_classes"]), dtype=torch.int64)
    val_loss = 0.0

    vis_cache = []

    pbar = tqdm(val_loader, total=len(val_loader), desc=f"Val {epoch:03d}")
    for images, masks, stems, img_paths, mask_paths in pbar:
        images = images.to(CFG["device"], non_blocking=True)
        masks = masks.to(CFG["device"], non_blocking=True)

        outputs = model(images)
        if isinstance(outputs, tuple):
            logits, aux_logits = outputs
            loss = criterion(logits, masks) + CFG["aux_weight"] * criterion(aux_logits, masks)
        else:
            logits = outputs
            loss = criterion(logits, masks)

        preds = torch.argmax(logits, dim=1)
        val_loss += float(loss.item())

        for b in range(images.size(0)):
            hist += fast_hist(preds[b].cpu(), masks[b].cpu(), CFG["num_classes"], CFG["ignore_index"])

            if len(vis_cache) < CFG["num_vis"]:
                vis_cache.append({
                    "image": images[b].detach().cpu(),
                    "mask": masks[b].detach().cpu(),
                    "pred": preds[b].detach().cpu(),
                    "stem": stems[b],
                })

    scores = compute_scores(hist)
    scores["val_loss"] = val_loss / max(1, len(val_loader))
    scores["hist"] = hist
    scores["vis_cache"] = vis_cache
    return scores

def denorm_image(x):
    x = x.clone()
    mean = torch.tensor(MEAN).view(3, 1, 1)
    std = torch.tensor(STD).view(3, 1, 1)
    x = x * std + mean
    x = x.clamp(0, 1)
    return x

def decode_mask(mask):
    # simple deterministic pseudo-color map
    mask = mask.numpy()
    h, w = mask.shape
    color = np.zeros((h, w, 3), dtype=np.uint8)
    for c in np.unique(mask):
        if c == CFG["ignore_index"]:
            color[mask == c] = np.array([0, 0, 0], dtype=np.uint8)
        else:
            rnd = np.random.RandomState(int(c) + 123)
            color[mask == c] = rnd.randint(0, 255, size=3)
    return color

def save_visualizations(vis_cache, epoch):
    if len(vis_cache) == 0:
        return
    fig, axes = plt.subplots(len(vis_cache), 3, figsize=(12, 4 * len(vis_cache)))
    if len(vis_cache) == 1:
        axes = np.expand_dims(axes, 0)
    for i, item in enumerate(vis_cache):
        img = denorm_image(item["image"]).permute(1, 2, 0).numpy()
        gt = decode_mask(item["mask"])
        pdm = decode_mask(item["pred"])

        axes[i, 0].imshow(img)
        axes[i, 0].set_title(f"{item['stem']} - image")
        axes[i, 1].imshow(gt)
        axes[i, 1].set_title("gt")
        axes[i, 2].imshow(pdm)
        axes[i, 2].set_title("pred")

        for j in range(3):
            axes[i, j].axis("off")

    vis_path = PATHS["work_dir"] / f"vis_epoch_{epoch:03d}.png"
    plt.tight_layout()
    plt.savefig(vis_path, dpi=150, bbox_inches="tight")
    plt.close(fig)

def append_metrics_csv(row_dict):
    row_df = pd.DataFrame([row_dict])
    if METRICS_CSV.exists():
        row_df.to_csv(METRICS_CSV, mode="a", header=False, index=False)
    else:
        row_df.to_csv(METRICS_CSV, mode="w", header=True, index=False)

# ============================================================
# START TRAINING
# ============================================================
print("=" * 100)
print("START TRAINING")
print("=" * 100)

for epoch in range(start_epoch, CFG["epochs"]):
    t0 = time.time()

    train_loss = train_one_epoch(epoch)

    do_eval = ((epoch + 1) % CFG["eval_every"] == 0) or (epoch == CFG["epochs"] - 1)
    if do_eval:
        scores = evaluate(epoch)
        val_loss = scores["val_loss"]
        aAcc = scores["aAcc"]
        mAcc = scores["mAcc"]
        mIoU = scores["mIoU"]
        mAcc_fg = scores["mAcc_fg"]
        mIoU_fg = scores["mIoU_fg"]

        save_visualizations(scores["vis_cache"], epoch)

        is_best = mIoU > best_miou
        if is_best:
            best_miou = mIoU
            save_checkpoint(BEST_CKPT, epoch, best_miou, global_step)

        save_checkpoint(LAST_CKPT, epoch, best_miou, global_step)

        epoch_time = time.time() - t0
        row = {
            "epoch": epoch,
            "train_loss": train_loss,
            "val_loss": val_loss,
            "aAcc": aAcc,
            "mAcc": mAcc,
            "mIoU": mIoU,
            "mAcc_fg": mAcc_fg,
            "mIoU_fg": mIoU_fg,
            "best_mIoU": best_miou,
            "lr": optimizer.param_groups[0]["lr"],
            "time_sec": epoch_time,
        }
        append_metrics_csv(row)

        print("-" * 100)
        print(
            f"Epoch {epoch:03d} | "
            f"train_loss={train_loss:.4f} | val_loss={val_loss:.4f} | "
            f"aAcc={aAcc:.4f} | mAcc={mAcc:.4f} | mIoU={mIoU:.4f} | "
            f"mAcc_fg={mAcc_fg:.4f} | mIoU_fg={mIoU_fg:.4f} | best={best_miou:.4f}"
        )

        # print per-class IoU for classes present in GT
        iou_per_class = scores["iou_per_class"]
        gt_sum = scores["gt_sum"]
        pred_sum = scores["pred_sum"]

        print("PER-CLASS IoU (classes present in GT)")
        present_ids = np.where(gt_sum > 0)[0]
        for cid in present_ids:
            cname = class_names[cid] if cid < len(class_names) else f"class_{cid}"
            print(
                f"id={cid:3d} | name={cname:20s} | "
                f"gt_pixels={int(gt_sum[cid]):8d} | pred_pixels={int(pred_sum[cid]):8d} | "
                f"IoU={float(iou_per_class[cid]):.4f}"
            )
        print("-" * 100)

print("=" * 100)
print("TRAINING DONE")
print(f"last checkpoint : {LAST_CKPT}")
print(f"best checkpoint : {BEST_CKPT}")
print(f"metrics csv     : {METRICS_CSV}")
print(f"config json     : {CONFIG_JSON}")
print("=" * 100)

# ============================================================
# VISUALIZE TEST MODEL
# - load best/last checkpoint
# - run inference on val/test set
# - save visualization grid
# ============================================================

@torch.no_grad()
def load_model_for_eval(ckpt_path):
    print(f"[LOAD FOR VIS] {ckpt_path}")
    ckpt = torch.load(ckpt_path, map_location=CFG["device"])
    model.load_state_dict(ckpt["model"], strict=True)
    model.eval()
    return ckpt

def overlay_mask_on_image(image_np, mask_np, alpha=0.45):
    """
    image_np: H,W,3 float [0,1]
    mask_np : H,W int
    """
    color_mask = decode_mask(torch.from_numpy(mask_np) if not isinstance(mask_np, torch.Tensor) else mask_np.cpu())
    color_mask = color_mask.astype(np.float32) / 255.0
    over = image_np * (1 - alpha) + color_mask * alpha
    return np.clip(over, 0, 1)

@torch.no_grad()
def visualize_test_model(
    loader,
    ckpt_path=None,
    num_samples=8,
    save_name="test_model_visualization.png",
    show_overlay=True,
):
    if ckpt_path is None:
        ckpt_path = BEST_CKPT if BEST_CKPT.exists() else LAST_CKPT

    if not Path(ckpt_path).exists():
        raise FileNotFoundError(f"Checkpoint not found: {ckpt_path}")

    load_model_for_eval(ckpt_path)

    samples = []
    pbar = tqdm(loader, total=len(loader), desc="Visualize test model")

    for images, masks, stems, img_paths, mask_paths in pbar:
        images = images.to(CFG["device"], non_blocking=True)

        outputs = model(images)
        if isinstance(outputs, tuple):
            logits = outputs[0]
        else:
            logits = outputs

        preds = torch.argmax(logits, dim=1).cpu()

        for b in range(images.size(0)):
            img = denorm_image(images[b].detach().cpu()).permute(1, 2, 0).numpy()
            gt = masks[b].cpu().numpy()
            pdm = preds[b].cpu().numpy()

            item = {
                "image": img,
                "gt": gt,
                "pred": pdm,
                "stem": stems[b],
            }

            if show_overlay:
                item["overlay_gt"] = overlay_mask_on_image(img, gt)
                item["overlay_pred"] = overlay_mask_on_image(img, pdm)

            samples.append(item)
            if len(samples) >= num_samples:
                break

        if len(samples) >= num_samples:
            break

    if len(samples) == 0:
        print("[WARN] No samples collected for visualization.")
        return

    # layout:
    # no overlay  -> image | gt | pred
    # overlay     -> image | gt | pred | overlay_gt | overlay_pred
    ncols = 5 if show_overlay else 3
    fig, axes = plt.subplots(len(samples), ncols, figsize=(4 * ncols, 4 * len(samples)))

    if len(samples) == 1:
        axes = np.expand_dims(axes, 0)

    for i, item in enumerate(samples):
        axes[i, 0].imshow(item["image"])
        axes[i, 0].set_title(f"{item['stem']} - image")
        axes[i, 1].imshow(decode_mask(torch.from_numpy(item["gt"])))
        axes[i, 1].set_title("ground truth")
        axes[i, 2].imshow(decode_mask(torch.from_numpy(item["pred"])))
        axes[i, 2].set_title("prediction")

        if show_overlay:
            axes[i, 3].imshow(item["overlay_gt"])
            axes[i, 3].set_title("overlay gt")
            axes[i, 4].imshow(item["overlay_pred"])
            axes[i, 4].set_title("overlay pred")

        for j in range(ncols):
            axes[i, j].axis("off")

    plt.tight_layout()
    save_path = PATHS["work_dir"] / save_name
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close(fig)

    print(f"[SAVED] {save_path}")

# ============================================================
# RUN VISUALIZATION
# ============================================================
# dùng best checkpoint nếu có, không thì last checkpoint
visualize_test_model(
    loader=val_loader,
    ckpt_path=BEST_CKPT if BEST_CKPT.exists() else LAST_CKPT,
    num_samples=8,
    save_name="test_model_visualization_best.png",
    show_overlay=True,
)